package com.intricatech.bitmap_shatter;

import android.view.MotionEvent;

/**
 * Created by Bolgbolg on 02/10/2017.
 */

public interface TouchDirector {

    /**
     * Add the calling object to the list of interested TouchObservers, to be notified in the
     * event of a TouchEvent.
     *
     * @param touchObserver The calling object.
     */
    public void register(TouchObserver touchObserver);

    /**
     * Unregister the calling object from the list of TouchObservers.
     * @param touchObserver The calling object.
     */
    public void unregister(TouchObserver touchObserver);

    /**
     * Pass the MotionEvent generated by the GameSurfaceView's TouchListener to observers that have
     * registered an interest.
     * @param me
     */
    public void updateObservers(MotionEvent me);
}
